version: '3'

services:
  db:
    image: mysql:8.4
    restart: always    
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=scrapyptt
      - MYSQL_DATABASE=ptt
      #- MYSQL_USER=root
      #- MYSQL_PASSWORD=ptt123
    ports: 
      - 8080:3306 
    volumes:
      - /ptt_scraper
  python_scrapy:
    build: .
    stdin_open: true
    tty: true
    command: scrapy crawl ptt -L "WARNING"